apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: flask-app-demo-stg
  namespace: flux-system
spec:
  interval: 30s
  chart:
    spec:
      chart: ./helm
      sourceRef:
        kind: GitRepository
        name: flask-app-demo
      interval: 1m
  targetNamespace: staging 
  values:
    #nodePort: 30001
    namespace: staging
    deployment:
      image: "oussamamaaroufi1/example-app-1"
      tag: "0.0.1"
    name: flask-demo-app-stg
  install:
    createNamespace: true  # Force the creatin of namespace if does not  exist in the cluster.
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
