apiVersion: helm.toolkit.fluxcd.io/v1beta1
kind: HelmRelease
metadata:
  name: flask-app-demo
  namespace: staging
spec:
  chart:
    spec:
      chart: helm
      sourceRef:
        kind: GitRepository
        name: flask-app-demo
        namespace: flux-system
      interval: 30s
  values:
    deployment:
      image: "oussamamaaroufi1/example-app-1"
      tag: "0.0.1"
    name: flask-demo-app