apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: grafana
  namespace: flux-system
spec:
  interval: 10m0s  # Flux will check repo every 10min if there is any update.
  url: https://grafana.github.io/helm-charts
