apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: flux-system
spec:
  interval: 60m
  releaseName: grafana
  targetNamespace: infrastructure
  chart:
    spec:
      chart: grafana
      version: 6.50.1
      sourceRef:
        kind: HelmRepository
        name: grafana
      interval: 30s
  install:
    remediation:
      retries: 1
    createNamespace: true
  upgrade:
    timeout: 30s
    remediation:
      retries: 1
      strategy: rollback
  values:
      service:
        type: NodePort
        nodePort: 30000
      image:
          repository: docker.io/grafana/grafana
          tag: ""
          sha: ""
